using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.IO.Pipes;
using System.Linq;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Text;

using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Tedd;

[Generator(LanguageNames.CSharp)]
public class StructCopyGenerator : IIncrementalGenerator // ISourceGenerator
{
    private const string attributeName = "GenerateReadOnlyStruct";
    private readonly SourceText GenerateReadOnlyAttributeSourceText = SourceText.From(@$"// Auto generated by {nameof(StructCopyGenerator)}
namespace Tedd;

/// <summary>
/// Generates a read-onlu version of a struct, with ReadOnly preceding name.
/// </summary>
[AttributeUsage(AttributeTargets.Struct)]
public class {attributeName}Attribute: Attribute 
{{
    private readonly bool _generateConstructor = true;
    private readonly bool _generateCopyConstructor = true;

    /// <summary>
    /// Generates a read-only version of a struct, with ReadOnly preceding name.
    /// </summary>
    /// <param name=""GenerateConstructor"">Generate constructor for all fields.</param>
    /// <param name=""GenerateCopyConstructor"">Generate constructor for copying from this type.</param>
    public {attributeName}Attribute(bool GenerateConstructor = true, bool GenerateCopyConstructor = true)
    {{
        _generateConstructor = GenerateConstructor;
        _generateCopyConstructor = GenerateCopyConstructor;
    }}

    /// <summary>
    /// Generate constructor for all fields.
    /// </summary>
    public bool GenerateConstructor => _generateConstructor;
    /// <summary>
    /// Generate constructor for copying from this type.
    /// </summary>
    public bool GenerateCopyConstructor => _generateCopyConstructor;
}}", Encoding.ASCII);

    public void Initialize(GeneratorInitializationContext context)
    {
        context.RegisterForPostInitialization(PostInitialization);
        // No initialization is required for this generator.
#if DEBUG
        if (!Debugger.IsAttached)
        {
            //Debugger.Launch();
            for (var i = 0; i < 10; i++)
                if (!System.Diagnostics.Debugger.IsAttached)
                    System.Threading.Thread.Sleep(1000);
            //System.Threading.Thread.Sleep(10000);
            //while (!System.Diagnostics.Debugger.IsAttached)
            //System.Threading.Thread.Sleep(5000);
        }
#endif 
        Debug.WriteLine("Initialize code generator");
    }


    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
#if DEBUG
        if (!Debugger.IsAttached)
        {
            //Debugger.Launch();
            for (var i = 0; i < 10; i++)
                if (!System.Diagnostics.Debugger.IsAttached)
                    System.Threading.Thread.Sleep(1000);
            //System.Threading.Thread.Sleep(10000);
            //while (!System.Diagnostics.Debugger.IsAttached)
            //System.Threading.Thread.Sleep(5000);
        }
#endif 
        Debug.WriteLine("Initialize code generator");

        context.RegisterPostInitializationOutput(PostInitialization);
        // Register filters
        // Big O Notation:
        // Time Complexity: O(1) for generator initialization pipeline setup.
        // Space Complexity: O(1) minimal closure allocations.
        var structDeclarations = context.SyntaxProvider.CreateSyntaxProvider(
            static (n, _) => n is StructDeclarationSyntax s && s.AttributeLists.Count > 0,
            static (n, _) => (StructDeclarationSyntax)n.Node)
            .Where(static m => m is not null);

        context.RegisterSourceOutput(structDeclarations, static (spc, source) => GenerateClass(spc, source));
    }


    private void PostInitialization(IncrementalGeneratorPostInitializationContext context)
    {
        // Add attribute
        context.AddSource("ReadOnlyGeneratorAttribute.cs", GenerateReadOnlyAttributeSourceText);
    }

    private void PostInitialization(GeneratorPostInitializationContext context)
    {
        // Add attribute
        context.AddSource("ReadOnlyGeneratorAttribute.cs", GenerateReadOnlyAttributeSourceText);
    }


    /// <summary>
    /// Generates the read-only struct implementation.
    /// Big O Notation:
    /// Time Complexity: O(M + P) where M is the number of members in the struct and P is the depth of the parent syntax tree nodes to resolve the namespace and using directives. This algorithm uses direct string appending (StringBuilder) to bypass expensive immutable syntax tree creation overhead (O(N) operations within Roslyn).
    /// Space Complexity: O(M) via StringBuilder and minimal List overheads, preventing huge SyntaxNode and SyntaxList allocations. Avoids deep 'NormalizeWhitespace' which can have extreme memory penalties for source generation.
    /// </summary>
    private static void GenerateClass(SourceProductionContext context, StructDeclarationSyntax structDeclaration)
    {
        Debug.WriteLine("Execute code generator");

        {
            foreach (var attributeList in structDeclaration.AttributeLists)
            {
                context.CancellationToken.ThrowIfCancellationRequested();
                // Check if the attribute is the one we're looking for.
                AttributeSyntax? generateReadOnlyStructAttribute = null;
                foreach (var attribute in attributeList.Attributes)
                {
                    if (attribute.Name.ToString() == attributeName)
                    {
                        generateReadOnlyStructAttribute = attribute;
                        break;
                    }
                }

                if (generateReadOnlyStructAttribute == null)
                    continue;

                var generateConstructor = generateReadOnlyStructAttribute.ArgumentList?.Arguments.Count > 0 && generateReadOnlyStructAttribute.ArgumentList?.Arguments[0].Expression.ToString() == "true";
                var generateCopyConstructor = generateReadOnlyStructAttribute.ArgumentList?.Arguments.Count > 1 && generateReadOnlyStructAttribute.ArgumentList?.Arguments[1].Expression.ToString() == "true";

                // Get name of struct
                var structName = structDeclaration.Identifier.Text;

                var ctorFields = new List<VariableDeclaratorSyntax>();
                var fieldsTypeMap = new Dictionary<VariableDeclaratorSyntax, string>();

                var sb = new StringBuilder();
                sb.AppendLine("#define RO_GEN");
                sb.AppendLine();
                sb.AppendLine($"// This file was generated by Tedd.{nameof(StructCopyGenerator)}");

                // Get root of document to resolve namespace and usings
                var root = (SyntaxNode)structDeclaration;
                string? nsStr = null;
                var usingsList = new List<UsingDirectiveSyntax>();

                while (root.Parent != null)
                {
                    root = root.Parent;
                    if (nsStr == null)
                    {
                        if (root is FileScopedNamespaceDeclarationSyntax fsNamespace)
                            nsStr = fsNamespace.Name.ToString();
                        else if (root is NamespaceDeclarationSyntax namespaceDecl)
                            nsStr = namespaceDecl.Name.ToString();
                    }
                    if (root is CompilationUnitSyntax compilationUnit)
                        usingsList.AddRange(compilationUnit.Usings);
                    else if (root is NamespaceDeclarationSyntax namespaceDeclWithUsings)
                        usingsList.AddRange(namespaceDeclWithUsings.Usings);
                }

                nsStr ??= "Error.Namespace.Not.Found";

                foreach (var u in usingsList)
                {
                    sb.AppendLine(u.ToFullString().Trim());
                }

                sb.AppendLine($"namespace {nsStr}");
                sb.AppendLine("{");

                // Write struct declaration modifiers
                var modifiers = structDeclaration.Modifiers.Where(m => !m.IsKind(SyntaxKind.ReadOnlyKeyword)).Select(m => m.Text).ToList();
                var modifiersStr = string.Join(" ", modifiers);
                if (!string.IsNullOrEmpty(modifiersStr)) modifiersStr += " ";

                // Copy attributes from the struct to the read-only struct
                foreach (var attr in structDeclaration.AttributeLists)
                {
                    sb.AppendLine($"    {attr.ToFullString().Trim()}");
                }

                sb.AppendLine($"    {modifiersStr}readonly struct ReadOnly{structName}");
                sb.AppendLine("    {");

                foreach (var member in structDeclaration.Members)
                {
                    if (member is FieldDeclarationSyntax field)
                    {
                        var fieldType = field.Declaration.Type.ToString();
                        var fieldModifiers = field.Modifiers.Select(m => m.Text).ToList();
                        if (!fieldModifiers.Contains("readonly") && !fieldModifiers.Contains("const"))
                        {
                            fieldModifiers.Add("readonly");
                        }

                        foreach (var attrList in field.AttributeLists)
                        {
                            sb.AppendLine($"        {attrList.ToFullString().Trim()}");
                        }

                        var fModifiersStr = string.Join(" ", fieldModifiers);
                        var fVarsStr = string.Join(", ", field.Declaration.Variables.Select(v =>
                        {
                            if (v.Initializer != null) return $"{v.Identifier.Text} {v.Initializer.ToFullString().Trim()}";
                            return v.Identifier.Text;
                        }));

                        sb.AppendLine($"        {fModifiersStr} {fieldType} {fVarsStr};");

                        foreach (var v in field.Declaration.Variables)
                        {
                            if (!field.Modifiers.Any(a => a.IsKind(SyntaxKind.ConstKeyword)))
                            {
                                ctorFields.Add(v);
                                fieldsTypeMap[v] = fieldType;
                            }
                        }
                    }
                    else if (member is ConstructorDeclarationSyntax constructor)
                    {
                        var ctorStr = constructor.WithIdentifier(SyntaxFactory.Identifier("ReadOnly" + structName)).ToFullString().Trim();
                        sb.AppendLine($"        {ctorStr}");
                    }
                    else
                    {
                        // Methods, Properties, etc.
                        sb.AppendLine($"        {member.ToFullString().Trim()}");
                    }
                }

                if (generateCopyConstructor)
                {
                    sb.AppendLine($"        public ReadOnly{structName}({structName} value)");
                    sb.AppendLine("        {");
                    foreach (var f in ctorFields)
                    {
                        sb.AppendLine($"            {f.Identifier.Text} = value.{f.Identifier.Text};");
                    }
                    sb.AppendLine("        }");
                }

                if (generateConstructor)
                {
                    var parameters = ctorFields.Select(f => $"{fieldsTypeMap[f]} {ToLowerFirstChar(f.Identifier.Text)}");
                    sb.AppendLine($"        public ReadOnly{structName}({string.Join(", ", parameters)})");
                    sb.AppendLine("        {");
                    foreach (var f in ctorFields)
                    {
                        sb.AppendLine($"            this.{f.Identifier.Text} = {ToLowerFirstChar(f.Identifier.Text)};");
                    }
                    sb.AppendLine("        }");
                }

                sb.AppendLine("    }");
                sb.AppendLine("}");

                var src = sb.ToString();
                var file = $"{nsStr}.{structName}.ReadOnlyStructs.cs";
                Debug.WriteLine("File generated: " + file);
                Debug.WriteLine(src);
                context.AddSource(file, SourceText.From(src, Encoding.UTF8));
            }
        }
    }



    private static string ToLowerFirstChar(string input)
    {
        if (string.IsNullOrEmpty(input))
            return input;

        return char.ToLower(input[0]) + input.Substring(1);
    }

}